#!/usr/bin/env python3
"""Generate CATALOG.md from block metadata (static parse — never executes
blocks). The plan skill must read the generated file IN FULL before
selecting blocks."""
import json
import os
import sys

import blocks


def _section(name, description, config, targets_text):
    lines = [f"## {name}", "", description, "",
             f"**Targets:** {targets_text}", "", "**Config:**", "",
             "```json", json.dumps(config, indent=2, sort_keys=True), "```", ""]
    return "\n".join(lines)


def generate(blocks_dir):
    out = ["<!-- generated by test-pilot catalog.py — do not edit by hand -->",
           "# Block CATALOG", "",
           "Every seeded mutation goes through a block listed here. "
           "Targets are the declared surfaces the protected-target gate "
           "checks.", ""]
    for name in sorted(blocks.BUILTIN_BLOCKS):
        meta = blocks.BUILTIN_BLOCKS[name]
        out.append(_section(name, meta["description"], meta["config"],
                            "declared per-scenario in the manifest config "
                            "(required, non-empty)"))
    for name, info in sorted(blocks.discover_blocks(blocks_dir).items()):
        meta = info["meta"]
        out.append(_section(name, meta.get("description", "(no description)"),
                            meta.get("config", {}),
                            "`" + "`, `".join(meta.get("targets", [])) + "`"))
    return "\n".join(out)


def main(argv):
    args = argv[1:]
    if "--blocks-dir" not in args:
        sys.stderr.write("usage: catalog.py --blocks-dir DIR\n")
        return 2
    d = args[args.index("--blocks-dir") + 1]
    try:
        text = generate(d)
    except blocks.BlockError as exc:
        sys.stderr.write(f"catalog error: {exc}\n")
        return 1
    with open(os.path.join(d, "CATALOG.md"), "w") as fh:
        fh.write(text)
    sys.stdout.write(os.path.join(d, "CATALOG.md") + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
