#!/usr/bin/env python3
"""Generate CATALOG.md from block metadata (static parse — never executes
blocks). The plan skill must read the generated file IN FULL before
selecting blocks."""
import json
import os
import sys

import blocks


def _section(name, description, config, targets_text):
    lines = [f"## {name}", "", description, "",
             f"**Targets:** {targets_text}", "", "**Config:**", "",
             "```json", json.dumps(config, indent=2, sort_keys=True), "```", ""]
    return "\n".join(lines)


def generate(blocks_dir):
    out = ["<!-- generated by test-pilot catalog.py — do not edit by hand -->",
           "# Block CATALOG", "",
           "Every seeded mutation goes through a block listed here. "
           "Targets are the declared surfaces the protected-target gate "
           "checks.", ""]
    for name in sorted(blocks.BUILTIN_BLOCKS):
        meta = blocks.BUILTIN_BLOCKS[name]
        out.append(_section(name, meta["description"], meta["config"],
                            "declared per-scenario in the manifest config "
                            "(required, non-empty)"))
    for name, info in sorted(blocks.discover_blocks(blocks_dir).items()):
        meta = info["meta"]
        raw_targets = meta.get("targets", [])
        if blocks.valid_targets(raw_targets):
            targets_text = "`" + "`, `".join(raw_targets) + "`"
        else:
            targets_text = "(none declared — INVALID)"
        out.append(_section(name, meta.get("description", "(no description)"),
                            meta.get("config", {}), targets_text))
    return "\n".join(out)


def _arg(args, flag, default=None):
    if flag in args:
        i = args.index(flag)
        if i + 1 < len(args) and not args[i + 1].startswith("--"):
            return args[i + 1]
    return default


def main(argv):
    args = argv[1:]
    d = _arg(args, "--blocks-dir")
    if not d:
        sys.stderr.write("usage: catalog.py --blocks-dir DIR\n")
        return 2
    if not os.path.isdir(d):
        sys.stderr.write(f"catalog error: blocks dir {d!r} does not exist\n")
        return 1
    try:
        text = generate(d)
    except blocks.BlockError as exc:
        sys.stderr.write(f"catalog error: {exc}\n")
        return 1
    try:
        with open(os.path.join(d, "CATALOG.md"), "w") as fh:
            fh.write(text)
    except OSError as exc:
        sys.stderr.write(f"catalog error: cannot write CATALOG.md: {exc}\n")
        return 1
    sys.stdout.write(os.path.join(d, "CATALOG.md") + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
